### ISSUE TITLE
Sliders missing 'slide'

### ISSUE THREAD

**Issue by cpressland** [catppuccin/home-assistant#11]
Hello, using Mocha variant, when a device is enabled the background 'slide' disappears from the slider.

Screenshot may make this considerably clearer:
<img width="416" alt="Screenshot 2023-04-07 at 10 43 20" src="https://user-images.githubusercontent.com/6557665/230586646-c99affb0-5847-4e51-a8f3-72ea7859ad48.png">

**Comment by labaland** [comment]
Bump!!!

**Comment by labaland** [comment]
very active theme

**Comment by fapfaff** [comment]
Sorry, I'm pretty busy lately and the used variables change frequently.  

I would be very grateful if you open a pull request fixing this issue and try to review and merge it asap.

**Comment by arunoruto** [comment]
I had the same issue and it seems to be fixed if you use the config I provided in #12 
You just have to change the colors for the dark theme and the name

**Comment by arunoruto** [comment]
> @arunoruto The config you posted in #12.... can I just replace what's in /config/themes/catppuccin/catppuccin.yaml with that?

@mattgphoto you can do that, but if an update happens, it will break things. You can also just create a new file and paste the yaml content there. If you don't like macchiato, change the colours to your scheme :) 

The reason for me not making a pull request, is a bigger change to the appearance of the dashboard, so I first wanted the opinion of the Devs if it's okay like that (even to have the frappe theme always as a light theme in there).

**Comment by mattgphoto** [comment]
@arunoruto Worked like a charm! Thank you very much for the path to get the theme working with slider buttons! 👍

**Comment by Makzimalist** [comment]
Opened a PullRequest for that. 
[Check here](https://github.com/catppuccin/home-assistant/pull/14)

**Comment by BlamBlaster** [comment]
The fact that this hasn't been resolved is mind blowing to me....

**Comment by fapfaff** [comment]
> Reference in new issue

it is already fixed. I just forgot to close the issue
