### ISSUE TITLE
New version of the theme

### ISSUE THREAD

**Issue by humrochagf** [catppuccin/home-assistant#16]
Hello!

Thanks for this nice theme it is my favorite HA theme :slightly_smiling_face: 

I noticed some of the issues that happens on latest versions of HA got already fixed in the repo.

Is it possible to have a new version release of the theme so we can update it in HA?

**Comment by fapfaff** [comment]
Sorry, I forgot that I have to create a new release, as I'm not using HA right now.
Thanks for the reminder!
I've created the release now.
