### ISSUE TITLE
thermostat icons are not visible

### ISSUE THREAD

**Issue by SiriosDev** [catppuccin/home-assistant#4]
thermostat icons are not showing, except the last one as you can see here: 
![image](https://user-images.githubusercontent.com/26876994/211216080-5b7f49ef-9996-4d49-9b2a-f3e8483f5eea.png)
As seen with the back-end selected:
![image](https://user-images.githubusercontent.com/26876994/211216123-f234de14-7777-4758-85c6-a54bf146bfcb.png)

**Comment by fapfaff** [comment]
duplicate of #1
