### ISSUE TITLE
Poor Contrast when "--text" is with "--sky" background

### ISSUE THREAD

**Issue by SiriosDev** [catppuccin/home-assistant#6]
Except for "Latte," this text is very poorly contrasted and almost illegible
![image](https://user-images.githubusercontent.com/26876994/212184443-b81cc6d6-040d-4c65-b303-c16bade78f76.png)

**Comment by a2nt** [comment]
some more examples of poor contrast
![Screenshot from 2023-03-20 02-27-31](https://user-images.githubusercontent.com/672794/226220198-498b3dbe-d2f9-4bc7-a91b-bd7c3a22da22.png)
